### ISSUE TITLE
no method named `parse2` found for struct `Pkcs12` in the current scope

### ISSUE THREAD

**Issue by stefiix92** [mvines/votalizer#4]
I did `./update-solana-dependencies.sh 1.18.16` and then `cargo build`. However, the build fails with the error

```
error[E0599]: no method named `parse2` found for struct `Pkcs12` in the current scope
   --> /home/solana/.cargo/registry/src/index.crates.io-6f17d22bba15001f/native-tls-0.2.12/src/imp/openssl.rs:162:29
    |
162 |         let parsed = pkcs12.parse2(pass)?;
    |                             ^^^^^^ help: there is a method with a similar name: `parse`

For more information about this error, try `rustc --explain E0599`
```

**Comment by mvines** [comment]
Curious why you care about updating the solana dependencies? I know votalizer is using an old version of the solana crates but 🤷🏼, doesn't really matter in general as the RPC interface votalizer uses remains backwards compatible

**Comment by stefiix92** [comment]
Alright, thanks for the heads up
